<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Markdig" Version="0.41.3" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3650.58" />
    <PackageVersion Include="MSTest" Version="4.0.2" />
    <PackageVersion Include="Tools.InnoSetup" Version="7.1.0" />
  </ItemGroup>
</Project>
