namespace Augit.App;

public static class UiText
{
    public const string AppName = "Augit";
    public const string OpenFolder = "打开目录";
    public const string Refresh = "刷新";
    public const string QuickOpen = "快速打开";
    public const string SearchWorkspace = "全仓搜索";
    public const string Settings = "设置";
    public const string Files = "文件";
    public const string GitChanges = "Git 改动";
    public const string GitSymbol = "G";
    public const string History = "历史";
    public const string HistorySymbol = "H";
    public const string TerminalSymbol = ">_";
    public const string Clone = "克隆";
    public const string InitializeRepository = "初始化仓库";
    public const string Fetch = "Fetch";
    public const string Pull = "Pull";
    public const string Push = "Push";
    public const string Remotes = "Remote";
    public const string CancelOperation = "取消操作";
    public const string Changes = "Changes";
    public const string UnversionedFiles = "Unversioned Files";
    public const string ToggleSelection = "勾选/取消";
    public const string SelectAllChanges = "全选 Changes";
    public const string SelectAllUnversioned = "全选未跟踪";
    public const string UnifiedDiff = "单栏";
    public const string SideBySideDiff = "双栏";
    public const string IgnoreWhitespace = "忽略空白";
    public const string CopyGitCommand = "复制 Git 命令";
    public const string PreviousChange = "上一处";
    public const string NextChange = "下一处";
    public const string DiffSearchPrompt = "查找 diff 文本";
    public const string ModifiedPreview = "修改后预览";
    public const string CommitMessage = "提交信息";
    public const string AmendLastCommit = "Amend last commit";
    public const string Commit = "Commit";
    public const string CommitAndPush = "Commit and Push";
    public const string PreviousPage = "上一页";
    public const string NextPage = "下一页";
    public const string ApplyFilter = "应用筛选";
    public const string ClearFilter = "清除筛选";
    public const string FilterMessage = "提交信息";
    public const string FilterHash = "哈希";
    public const string FilterAuthor = "作者";
    public const string FilterSince = "起始日期";
    public const string FilterUntil = "结束日期";
    public const string FilterBranch = "分支";
    public const string FilterFile = "文件路径";
    public const string CompareReferences = "比较引用";
    public const string ManageReferences = "分支与标签";
    public const string ManageLocalState = "Stash 与 Reset";
    public const string ManageWorktrees = "Worktree";
    public const string AdvancedGitOperations = "高级操作";
    public const string FileHistory = "文件历史";
    public const string Blame = "Blame";
    public const string HistoryLoading = "正在读取提交历史…";
    public const string HistoryReady = "提交历史已刷新。";
    public const string HistoryUnavailable = "当前工作区没有可显示的 Git 历史。";
    public const string SelectCommit = "请选择提交查看元数据和变化文件。";
    public const string SelectCommitFile = "请选择提交中的变化文件查看 diff。";
    public const string ComparisonBasePrompt = "基准引用";
    public const string ComparisonTargetPrompt = "目标引用（留空表示工作区）";
    public const string ComparisonPathPrompt = "文件路径（留空表示全部）";
    public const string InvalidDateFilter = "日期筛选必须使用可识别的日期或 ISO 8601 时间。";
    public const string HistoryPanelCreateFailed = "无法创建 Git 历史面板。";
    public const string HistoryPanelClassRegisterFailed = "无法注册 Git 历史面板窗口类。";
    public const string HistoryControlCreateFailed = "无法创建 Git 历史界面控件。";
    public const string GitTextWindowCreateFailed = "无法创建 Git 只读结果窗口。";
    public const string GitTextWindowClassRegisterFailed = "无法注册 Git 只读结果窗口类。";
    public const string GitTextControlCreateFailed = "无法创建 Git 只读结果控件。";
    public const string Branches = "本地与远程分支";
    public const string Tags = "标签";
    public const string ReferenceName = "名称";
    public const string ReferenceTarget = "起点 / 上游 / Remote";
    public const string TagMessage = "标签说明（留空为轻量标签）";
    public const string CreateBranch = "创建分支";
    public const string SwitchBranch = "切换分支";
    public const string RenameBranch = "重命名";
    public const string DeleteBranch = "删除分支";
    public const string ForceDeleteBranch = "强制删除未合并分支";
    public const string CreateTrackingBranch = "从远程创建跟踪分支";
    public const string UnsetTracking = "取消跟踪";
    public const string CreateTag = "创建标签";
    public const string DeleteLocalTag = "删除本地标签";
    public const string PushTag = "推送标签";
    public const string DeleteRemoteTag = "删除远端标签";
    public const string ReferenceManagement = "分支与标签管理";
    public const string ReferenceDialogCreateFailed = "无法创建分支与标签管理窗口。";
    public const string ReferenceDialogClassRegisterFailed = "无法注册分支与标签管理窗口类。";
    public const string ReferenceDialogControlCreateFailed = "无法创建分支与标签管理控件。";
    public const string SelectBranchFirst = "请先选择分支。";
    public const string SelectTagFirst = "请先选择标签。";
    public const string ConfirmDeleteBranch = "删除分支会移除该分支引用；强制删除还可能丢失未合并提交，确定继续吗？";
    public const string ConfirmDeleteTag = "删除标签会移除该标签引用，确定继续吗？";
    public const string ConfirmDeleteRemoteTag = "删除远端标签会修改远端仓库，确定继续吗？";
    public const string ReferenceOperationCompleted = "分支或标签操作已完成。";
    public const string Stashes = "Stash 列表";
    public const string StashMessage = "Stash 说明";
    public const string ResetTarget = "Reset 目标";
    public const string CreateStash = "Stash";
    public const string CreateStashWithUntracked = "Stash 含未跟踪";
    public const string ApplyStash = "应用并保留";
    public const string PopStash = "应用并删除";
    public const string ViewStash = "查看内容";
    public const string ResetSoft = "Reset Soft";
    public const string ResetMixed = "Reset Mixed";
    public const string ResetHard = "Reset Hard";
    public const string LocalStateManagement = "Stash 与 Reset";
    public const string LocalStateDialogCreateFailed = "无法创建 Stash 与 Reset 窗口。";
    public const string LocalStateDialogClassRegisterFailed = "无法注册 Stash 与 Reset 窗口类。";
    public const string LocalStateDialogControlCreateFailed = "无法创建 Stash 与 Reset 控件。";
    public const string SelectStashFirst = "请先选择 Stash。";
    public const string ConfirmResetSoft = "Reset Soft 会移动当前分支但保留索引和工作区，确定继续吗？";
    public const string ConfirmResetMixed = "Reset Mixed 会移动当前分支并重置索引，但保留工作区文件，确定继续吗？";
    public const string ConfirmResetHard = "Reset Hard 会丢弃索引和工作区改动，此操作不可由 Augit 撤销，确定继续吗？";
    public const string LocalStateOperationCompleted = "本地状态操作已完成。";
    public const string Worktrees = "Worktree 列表";
    public const string WorktreePath = "目标路径";
    public const string WorktreeSourceBranch = "来源分支";
    public const string WorktreeNewBranch = "新分支（留空则使用来源分支）";
    public const string CreateAndOpenWorktree = "创建并打开";
    public const string OpenWorktree = "打开";
    public const string RemoveWorktree = "安全移除";
    public const string WorktreeManagement = "Worktree 管理";
    public const string WorktreeDialogCreateFailed = "无法创建 Worktree 管理窗口。";
    public const string WorktreeDialogClassRegisterFailed = "无法注册 Worktree 管理窗口类。";
    public const string WorktreeDialogControlCreateFailed = "无法创建 Worktree 管理控件。";
    public const string SelectWorktreeFirst = "请先选择 Worktree。";
    public const string ConfirmRemoveWorktree = "只会在 Worktree 干净时调用 git worktree remove，不会强制删除，确定继续吗？";
    public const string WorktreeOperationCompleted = "Worktree 操作已完成。";
    public const string ReadingWorktrees = "正在读取 Worktree…";
    public const string RunningWorktreeOperation = "正在执行 Worktree 操作…";
    public const string WorktreeOpened = "已在独立 Augit 窗口打开 Worktree。";
    public const string WorktreeDirectoryMissing = "Worktree 目录不存在，无法打开。";
    public const string AugitExecutableUnavailable = "无法确定当前 Augit 可执行文件，不能打开独立窗口。";
    public const string Rollback = "Rollback";
    public const string ConfirmRollback = "Rollback 会丢弃所选完整文件的当前 diff；未跟踪或新增文件会进入 Windows 回收站，确定继续吗？";
    public const string SelectRollbackFile = "请先选择要 Rollback 的文件。";
    public const string RollbackConflictUnavailable = "冲突文件必须在阶段四的冲突流程中处理，不能直接 Rollback。";
    public const string RollingBack = "正在 Rollback 所选完整文件…";
    public const string RollbackCompleted = "所选文件已完成 Rollback。";
    public const string GitOperationManagement = "Git 操作与冲突";
    public const string OperationKind = "操作";
    public const string OperationTarget = "目标提交、分支或标签";
    public const string StartOperation = "执行";
    public const string SmartCheckout = "Smart Checkout";
    public const string ContinueOperation = "Continue";
    public const string SkipOperation = "Skip";
    public const string AbortOperation = "Abort";
    public const string ResolveConflict = "打开三栏解决器";
    public const string AcceptYours = "Accept Yours";
    public const string AcceptTheirs = "Accept Theirs";
    public const string OpenConflictExternally = "使用外部工具";
    public const string ConflictFiles = "冲突文件";
    public const string NoOperation = "当前没有进行中的 Git 操作或冲突。";
    public const string SelectConflictFile = "请先选择冲突文件。";
    public const string ConflictTextUnavailable = "该文件不是不超过 10 MB 的有效 UTF-8 文本，不能进入三栏编辑。";
    public const string GitOperationDialogCreateFailed = "无法创建 Git 操作与冲突窗口。";
    public const string GitOperationDialogClassRegisterFailed = "无法注册 Git 操作与冲突窗口类。";
    public const string GitOperationDialogControlCreateFailed = "无法创建 Git 操作与冲突控件。";
    public const string ConflictResolver = "三栏冲突解决器";
    public const string FinalResult = "最终结果";
    public const string AcceptLeftBlock = "接受左侧块";
    public const string AcceptRightBlock = "接受右侧块";
    public const string AcceptBothBlock = "接受两侧块";
    public const string SaveAndResolve = "保存并标记已解决";
    public const string ConflictResolverCreateFailed = "无法创建三栏冲突解决器窗口。";
    public const string ConflictResolverClassRegisterFailed = "无法注册三栏冲突解决器窗口类。";
    public const string ConflictResolverControlCreateFailed = "无法创建三栏冲突解决器控件。";
    public const string UnresolvedConflictBlocks = "仍有未处理的冲突块。";
    public const string ConflictResolved = "冲突文件已保存并由 Git 标记为已解决。";
    public const string ExternalConflictChanged = "冲突文件已被外部工具修改。选择“是”重新载入外部内容，选择“否”保留当前未保存内容。";
    public const string NoWorkspace = "打开一个本地目录开始浏览";
    public const string NoDocument = "从左侧文件树打开文件";
    public const string CopyPath = "复制路径";
    public const string RevealInExplorer = "在资源管理器中定位";
    public const string OpenExternalTerminal = "在外部终端打开";
    public const string RecentWorkspaces = "最近目录";
    public const string NoRecentWorkspaces = "没有最近打开的目录。";
    public const string Terminal = "终端";
    public const string CloseTerminal = "关闭终端";
    public const string TerminalShell = "终端 Shell";
    public const string WindowsPowerShell = "Windows PowerShell";
    public const string PowerShell7 = "PowerShell 7";
    public const string CommandPrompt = "CMD";
    public const string GitBash = "Git Bash";
    public const string Wsl = "WSL";
    public const string CustomTerminal = "自定义命令";
    public const string TerminalCustomCommand = "自定义启动命令";
    public const string TerminalDescription = "首次默认使用 Windows PowerShell；配置失效时终端会明确报错，不会切换到其他 Shell。";
    public const string TerminalCustomCommandRequired = "选择自定义终端时必须填写启动命令。";
    public const string TerminalLoading = "正在按需创建内置终端…";
    public const string TerminalReady = "内置终端已启动。";
    public const string TerminalClosed = "内置终端已关闭。";
    public const string TerminalStartFailed = "内置终端启动失败。";
    public const string TerminalHostCreateFailed = "无法创建终端显示宿主。";
    public const string TerminalControlCreateFailed = "无法创建终端界面控件。";
    public const string TerminalAssetsMissing = "随程序附带的终端显示组件缺失。";
    public const string TerminalSessionAlreadyActive = "当前工作区已有内置终端会话。";
    public const string TerminalInputFailed = "无法向内置终端发送输入。";
    public const string TerminalResizeFailed = "无法同步内置终端尺寸。";
    public const string ConfirmCloseRunningTerminal = "终端中存在可能仍在运行的前台命令。关闭终端将结束该命令、Shell 及其整个子进程树，确定继续吗？";
    public const string Close = "关闭";
    public const string Original = "原文";
    public const string Preview = "预览";
    public const string Formatted = "格式化";
    public const string Split = "对照";
    public const string Find = "查找";
    public const string GoToLine = "跳转行";
    public const string WordWrap = "自动换行";
    public const string ShowWhitespace = "显示空白符";
    public const string OpenExternally = "用系统默认程序打开";
    public const string Previous = "上一个";
    public const string Next = "下一个";
    public const string MatchCase = "区分大小写";
    public const string MatchWholeWord = "全字匹配";
    public const string RegularExpression = "正则表达式";
    public const string IncludeIgnoredFiles = "包含忽略文件";
    public const string SelectWorkspace = "选择工作区目录";
    public const string QuickOpenFiles = "快速打开文件";
    public const string WorkspaceTextSearch = "全仓文本搜索";
    public const string FollowWindows = "跟随 Windows";
    public const string Light = "浅色";
    public const string Dark = "深色";
    public const string Theme = "主题";
    public const string InterfaceFont = "界面字体";
    public const string MonospaceFont = "等宽字体";
    public const string FontSize = "字号";
    public const string GitExecutable = "Git 可执行文件";
    public const string GitExecutableDescription = "留空时使用系统 PATH 中的 git.exe；最低支持 Git for Windows 2.40。";
    public const string AppearanceDescription = "主题覆盖主界面和预览；字体设置只改变显示，不会修改文件。";
    public const string Cancel = "取消";
    public const string Confirm = "确定";
    public const string LineNumber = "行号";
    public const string GoTo = "跳转";
    public const string CloseSymbol = "×";
    public const string FilesSymbol = "☰";
    public const string SearchSymbol = "⌕";
    public const string InvalidDirectory = "无法打开此目录。";
    public const string WorkspaceOpened = "工作区已打开。";
    public const string RestorePartiallyFailed = "部分文件树状态无法恢复。";
    public const string WorkspaceAlreadyOpen = "该目录已在另一个窗口中打开。";
    public const string DirectoryReadFailed = "目录无法读取。";
    public const string ReadingFile = "正在读取文件…";
    public const string OpenWorkspaceFirst = "请先打开工作区。";
    public const string SearchComponentMissing = "随程序附带的搜索组件缺失。";
    public const string Searching = "正在搜索…";
    public const string SearchComponentFailed = "搜索组件无法启动。";
    public const string PathCopied = "路径已复制。";
    public const string ClipboardUnavailable = "剪贴板当前不可用。";
    public const string TreeRefreshed = "文件树已刷新。";
    public const string ExternalChangesSynchronized = "已同步外部文件变化。";
    public const string AppearanceFontSizeError = "字号必须在 9 到 40 之间。";
    public const string MarkdownRuntimeMissing = "Markdown 预览不可用，请安装兼容的 Microsoft Edge WebView2 Runtime。";
    public const string WebView2RuntimeMissing = "缺少兼容的 Microsoft Edge WebView2 Runtime。是否打开微软官方下载页面？";
    public const string ImageDecodeFailed = "图片解码失败，已停止预览。";
    public const string FindLocated = "已定位";
    public const string FindNotFound = "未找到";
    public const string InvalidRegularExpression = "正则表达式无效";
    public const string FindTimedOut = "查找超时";
    public const string FolderDialogUnavailable = "系统目录选择器不可用。";
    public const string WicUnavailable = "Windows 图片解码组件不可用。";
    public const string ImageDimensionsOutOfRange = "图片尺寸超出预览范围。";
    public const string ImageBitmapCreateFailed = "无法创建图片预览位图。";
    public const string DocumentViewCreateFailed = "无法创建文档查看区域。";
    public const string DocumentViewClassRegisterFailed = "无法注册文档查看窗口类。";
    public const string DocumentControlCreateFailed = "无法创建文档界面控件。";
    public const string ExternalProgramFailed = "无法启动外部程序。";
    public const string ReadOnlyTextControlCreateFailed = "无法创建只读文本控件。";
    public const string ScintillaMissing = "Scintilla 原生组件缺失或无法加载。";
    public const string AppearanceWindowCreateFailed = "无法创建外观设置窗口。";
    public const string AppearanceWindowClassRegisterFailed = "无法注册外观设置窗口类。";
    public const string AppearanceControlCreateFailed = "无法创建外观设置控件。";
    public const string InputWindowCreateFailed = "无法创建输入窗口。";
    public const string InputWindowClassRegisterFailed = "无法注册输入窗口类。";
    public const string InputControlCreateFailed = "无法创建输入控件。";
    public const string MarkdownHostCreateFailed = "无法创建 Markdown 预览宿主。";
    public const string WebViewLoaderMissing = "WebView2 原生加载组件缺失或无法加载。";
    public const string SearchPanelCreateFailed = "无法创建搜索面板。";
    public const string SearchPanelClassRegisterFailed = "无法注册搜索面板窗口类。";
    public const string SearchControlCreateFailed = "无法创建搜索控件。";
    public const string MainWindowCreateFailed = "无法创建 Augit 主窗口。";
    public const string MainWindowCloseFailed = "无法关闭 Augit 主窗口。";
    public const string StartupWorkspaceOwnershipReleased = "启动工作区所有权已经释放。";
    public const string MainWindowClassRegisterFailed = "无法注册 Augit 主窗口类。";
    public const string CommonControlsInitializeFailed = "无法初始化 Windows 原生控件。";
    public const string InterfaceControlCreateFailed = "无法创建 Augit 原生界面控件。";
    public const string TreeNodeInsertFailed = "无法插入文件树节点。";
    public const string AppearanceApplied = "外观设置已应用。";
    public const string SettingsApplied = "设置已应用。";
    public const string GitPanelCreateFailed = "无法创建 Git 改动面板。";
    public const string GitPanelClassRegisterFailed = "无法注册 Git 改动面板窗口类。";
    public const string GitControlCreateFailed = "无法创建 Git 界面控件。";
    public const string GitUnavailable = "Git 模块不可用。";
    public const string GitRefreshing = "正在刷新 Git 状态…";
    public const string GitReady = "Git 状态已刷新。";
    public const string NoGitChanges = "工作区没有本地改动。";
    public const string SelectGitFile = "从左侧选择文件查看 diff。";
    public const string NoTextDiff = "当前选项下没有文本差异。";
    public const string BinaryDiffSummary = "二进制文件发生变化，不显示正文 diff。";
    public const string DiffSideTooLarge = "新旧任一侧超过 10 MB，不显示正文 diff。";
    public const string DiffOutputTooLarge = "生成的 diff 超过 20 MB，不显示正文 diff。";
    public const string RepositoryInitialized = "Git 仓库已初始化。";
    public const string CommitCompleted = "提交已完成。";
    public const string CommitAndPushCompleted = "提交并推送已完成。";
    public const string FetchCompleted = "Fetch 已完成。";
    public const string PullCompleted = "Pull 已完成。";
    public const string PushCompleted = "Push 已完成。";
    public const string CloneWindowCreateFailed = "无法创建克隆窗口。";
    public const string CloneWindowClassRegisterFailed = "无法注册克隆窗口类。";
    public const string CloneControlCreateFailed = "无法创建克隆界面控件。";
    public const string CloneSource = "仓库地址";
    public const string CloneDestination = "目标目录";
    public const string Browse = "浏览…";
    public const string Cloning = "正在克隆…";
    public const string CloneCompleted = "克隆已完成。";
    public const string CloneFailed = "Git 克隆失败。";
    public const string SelectCloneDestination = "选择克隆目标目录";
    public const string RemoteManagement = "Remote 管理";
    public const string RemoteName = "名称";
    public const string RemoteFetchUrl = "Fetch 地址";
    public const string RemotePushUrl = "Push 地址（留空则同 Fetch）";
    public const string Add = "新增";
    public const string Save = "保存";
    public const string Delete = "删除";
    public const string LocalBranch = "本地分支";
    public const string RemoteBranch = "远端分支";
    public const string SetTracking = "设置跟踪";
    public const string RemoteOperationCompleted = "Remote 设置已更新。";
    public const string RemoteDialogCreateFailed = "无法创建 Remote 管理窗口。";
    public const string RemoteDialogClassRegisterFailed = "无法注册 Remote 管理窗口类。";
    public const string RemoteDialogControlCreateFailed = "无法创建 Remote 管理界面控件。";
    public const string SelectRemoteFirst = "请先选择一个 remote。";
    public const string PullRepositoryConfigured = "按仓库配置";
    public const string PullMerge = "Merge";
    public const string PullRebase = "Rebase";
    public const string PullFastForwardOnly = "Fast-forward only";
    public const string PlainDirectoryGitStatus = "当前目录尚未初始化 Git 仓库";
    public const string PlainDirectoryGitNotice = "当前目录尚未初始化 Git 仓库，可从上方显式初始化。";
    public const string BareRepositoryGitStatus = "当前目录是 bare 仓库，没有可显示的工作区改动";
    public const string BareRepositoryGitNotice = "Bare 仓库没有工作区，Changes 不可用。";
    public const string NoCommits = "尚无提交";
    public const string StagedAndModified = " 已暂存+后续修改";
    public const string Staged = " 已暂存";
    public const string InitializingRepository = "正在初始化 Git 仓库…";
    public const string InitializeRepositoryFailed = "Git 初始化失败。";
    public const string GeneratingDiff = "正在生成 diff…";
    public const string GenerateDiffFailed = "无法生成 diff。";
    public const string Committing = "正在提交…";
    public const string CommittingAndPushing = "正在提交并推送…";
    public const string CommitFailed = "提交失败。";
    public const string GitRemoteOperationRunning = "正在执行 Git 远程操作…";
    public const string GitRemoteOperationFailed = "Git 远程操作失败。";
    public const string ReadingRemotes = "正在读取 remote…";
    public const string ReadRemotesFailed = "无法读取 remote。";
    public const string UpdatingRemotes = "正在更新 remote…";
    public const string RemoteOperationFailed = "Remote 操作失败。";
    public const string ImageViewCreateFailed = "无法创建图片预览控件。";
    public const string ImageViewClassRegisterFailed = "无法注册图片预览窗口类。";

    public static string FileCount(int count) => $"{count} 个文件";

    public static string SearchResultCount(int count) => $"{count} 条结果";

    public static string SymbolicLinkTarget(string path) => $"符号链接目标：{path}";

    public static string JsonError(long? line, long? column) => $"JSON 格式错误：第 {line} 行，第 {column} 列。";

    public static string DocumentSummary(string type, string size, string path) => $"类型：{type}\n大小：{size}\n路径：{path}";

    public static string BlockedImage(string source) => $"[已阻止图片：{source}]";

    public static string StartupFailed(string message) => $"Augit 无法启动。\n\n{message}";

    public static string GitBranchStatus(string? branch, bool detached, int changes, int unversioned)
    {
        string current = detached ? $"Detached HEAD：{branch}" : $"分支：{branch ?? NoCommits}";
        return $"{current}    Changes {changes}    Unversioned {unversioned}";
    }

    public static string GitGroup(string title, int count) => $"▾ {title} ({count})";

    public static string GitDiffSizes(string notice, string oldSize, string newSize)
        => $"{notice}\n\n旧侧：{oldSize}\n新侧：{newSize}";

    public static string CommitCompletedPushFailed(string? error) => $"提交已完成，但 Push 失败：{error}";

    public static string RemoteCount(int count) => $"{count} 个 remote";

    public static string ConfirmDeleteRemote(string name) => $"确定删除 remote {name} 吗？";

    public static string WorktreeCount(int count) => $"{count} 个 Worktree";

    public static string TerminalTitle(string shell, string workspace)
        => $"{Terminal}  ·  {shell}  ·  {workspace}";

    public static string TerminalExited(int exitCode) => $"内置终端已退出，退出码 {exitCode}。";

    public static string ConfirmRemoveWorktreeDetails(string path, string? branch)
        => $"路径：{path}\n分支：{branch ?? "Detached HEAD"}\n\n{ConfirmRemoveWorktree}";

    public static string ConfirmRollbackDetails(string path, string oldSize, string newSize, bool recycle)
    {
        string result = recycle ? "文件将移入 Windows 回收站。" : "文件将恢复为 HEAD 中的完整内容。";
        return $"文件：{path}\n旧侧：{oldSize}\n新侧：{newSize}\n影响：{result}\n\n{ConfirmRollback}";
    }

    public static string ConfirmDeleteBranchDetails(string name, bool force)
        => $"分支：{name}\n删除方式：{(force ? "强制删除，未合并提交可能丢失" : "仅在已经合并时删除")}\n\n{ConfirmDeleteBranch}";

    public static string ConfirmDeleteTagDetails(string name, bool remote, string? remoteName)
        => remote
            ? $"标签：{name}\n远端：{remoteName}\n\n{ConfirmDeleteRemoteTag}"
            : $"标签：{name}\n\n{ConfirmDeleteTag}";

    public static string ConfirmResetDetails(string target, string warning)
        => $"目标：{target}\n\n{warning}";
}
